baseURL = "https://wangyujie1207.github.io"
languageCode = "zh-CN"
title = "Wangyujie"
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

DefaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false

[Languages]
[languages.zh]
  languageCode = "zh-CN"
  languageName = "简体中文"

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[params]
    since = 2017
    author = "Wangyujie"                           # Author's name
    avatar = "/images/avatar.jpg"           # Author's avatar
    subtitle = "我会更好，因为我没有停止"         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
   
    description = "" # site description
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""

[params.social]
    GitHub = "wangyujie1207"
    Email   = "82414199@163.com"
    # Instagram = "xxoo"
    # Wechat = "/images/me/wechat.png"  # Wechat QRcode image
    # Facebook = "xxoo"
    # Telegram = "xxoo"
    # Dribbble = "xxoo"
    # Medium = "xxoo"

